version: "3.9"

services:
  web:
    build: ./src
    command: gunicorn fampay.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - web_root:/backend/
      - static_volume:/backend/static
      - media_volume:/backend/media
    expose:
      - 8000
    env_file:
      - ./src/docker.env
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/docker.env

  nginx:
    build: ./webserver
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis_data:/data

  celery:
    restart: always
    build:
      context: ./src
    command: celery -A fampay.celery worker -l info
    volumes:
      - web_root:/app
    depends_on:
      - db
      - redis
      - web

  worker:
    restart: always
    build:
      context: ./src
    command: celery -A fampay.celery beat -l info
    volumes:
      - web_root:/app
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  web_root:
  redis_data: