version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "0.0.0.0:8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
             
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=fampay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0.0.0.0:5432:5432"
